#include "tables.h"

namespace ccc::mips {

const InsnInfo* INSN_TABLES[MAX_INSN_CLASS] = {
	MIPS_OPCODE_TABLE,
	MIPS_SPECIAL_TABLE,
	MIPS_REGIMM_TABLE,
	MMI_TABLE,
	MMI0_TABLE,
	MMI1_TABLE,
	MMI2_TABLE,
	MMI3_TABLE,
	COP0_TABLE,
	COP0_BC0_TABLE,
	COP0_C0_TABLE,
	COP1_TABLE,
	COP1_BC1_TABLE,
	COP1_S_TABLE,
	COP1_W_TABLE
};

using IT = InsnType;
using FD = FlowDirection;
using FT = FlowType;
using IF = InsnField;
using RC = RegisterClass;

extern const InsnInfo MIPS_OPCODE_TABLE[MAX_OPCODE] = {
	{"special" , IT::INVALD},
	{"regimm"  , IT::INVALD},
	{"j"       , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, FT::IMMED, IF::TARGET}}},
	{"jal"     , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::OUT, GPR::RA}         , {FD::IN, FT::IMMED, IF::TARGET}}},
	{"beq"     , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}}},
	{"bne"     , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}}},
	{"blez"    , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, RC::GPR, IF::IMMED}}},
	{"bgtz"    , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, RC::GPR, IF::IMMED}}},
	{"addi"    , IT::ARTMTC, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"addiu"   , IT::ARTMTC, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"slti"    , IT::ARTMTC, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"sltiu"   , IT::ARTMTC, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"andi"    , IT::ARTMTC, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"ori"     , IT::ARTMTC, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"xori"    , IT::ARTMTC, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"lui"     , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}}},
	{"cop0"    , IT::INVALD},
	{"cop1"    , IT::INVALD},
	{"cop2"    , IT::INVALD},
	{"resvd_19", IT::INVALD},
	{"beql"    , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"bnel"    , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"blezl"   , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"bgtzl"   , IT::BRANCH, {{FD::OUT  , SpecialGPR::PC} , {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"daddi"   , IT::INVALD, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"daddiu"  , IT::INVALD, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, RC::GPR  , IF::RS}   , {FD::IN, FT::IMMED, IF::IMMED}}},
	{"ldl"     , IT::LOADFM, {{FD::INOUT, RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"ldr"     , IT::LOADFM, {{FD::INOUT, RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"mmi"     , IT::INVALD},
	{"resvd_29", IT::INVALD},
	{"lq"      , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"sq"      , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lb"      , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lh"      , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lwl"     , IT::LOADFM, {{FD::INOUT, RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lw"      , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lbu"     , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lhu"     , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lwr"     , IT::LOADFM, {{FD::INOUT, RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"lwu"     , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"sb"      , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"sh"      , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"swl"     , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"sw"      , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"sdl"     , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"sdr"     , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"swr"     , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"cache"   , IT::SYSTEM},
	{"unsup_48", IT::INVALD},
	{"lwc1"    , IT::LOADFM, {{FD::OUT  , RC::FPU, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"unsup_50", IT::INVALD},
	{"pref"    , IT::SYSTEM},
	{"unsup_52", IT::INVALD},
	{"unsup_53", IT::INVALD},
	{"lqc2"    , IT::LOADFM, {{FD::OUT  , RC::VU0, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"ld"      , IT::LOADFM, {{FD::OUT  , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"unsup_56", IT::INVALD},
	{"swc1"    , IT::LOADFM, {{FD::IN   , RC::FPU, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"unsup_58", IT::INVALD},
	{"resvd_59", IT::INVALD},
	{"unsup_60", IT::INVALD},
	{"unsup_61", IT::INVALD},
	{"sqc2"    , IT::LOADFM, {{FD::IN   , RC::VU0, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}},
	{"sd"      , IT::STOREM, {{FD::IN   , RC::GPR, IF::RT}, {FD::IN, FT::IMMED, IF::IMMED}, {FD::IN, RC::GPR, IF::RS}}}
};

extern const InsnInfo MIPS_SPECIAL_TABLE[MAX_SPECIAL] = {
	{"sll"},
	{"resvd_1"},
	{"srl"},
	{"sra"},
	{"sllv"},
	{"resvd_5"},
	{"srlv"},
	{"srav"},
	{"jr"},
	{"jalr"},
	{"movz"},
	{"movn"},
	{"syscall"},
	{"break"},
	{"resvd_14"},
	{"sync"},
	{"mfhi"},
	{"mthi"},
	{"mflo"},
	{"mtlo"},
	{"dsllv"},
	{"resvd_"},
	{"dsrlv"},
	{"dsrav"},
	{"mult"},
	{"multu"},
	{"div"},
	{"divu"},
	{"unsup_"},
	{"unsup_29"},
	{"unsup_30"},
	{"unsup_31"},
	{"add"},
	{"addu"},
	{"sub"},
	{"subu"},
	{"and"},
	{"or"},
	{"xor"},
	{"nor"},
	{"mfsa"},
	{"mtsa"},
	{"slt"},
	{"sltu"},
	{"dadd"},
	{"daddu"},
	{"dsub"},
	{"dsubu"},
	{"tge"},
	{"tgeu"},
	{"tlt"},
	{"tltu"},
	{"teq"},
	{"resvd_53"},
	{"tne"},
	{"resvd_55"},
	{"dsll"},
	{"resvd"},
	{"dsrl"},
	{"dsra"},
	{"dsll32"},
	{"resvd_61"},
	{"dsrl32"},
	{"dsra32"}
};

extern const InsnInfo MIPS_REGIMM_TABLE[MAX_REGIMM] = {
	{"bltz"},
	{"bgez"},
	{"bltzl"},
	{"bgezl"},
	{"resvd_4"},
	{"resvd_5"},
	{"resvd_6"},
	{"resvd_7"},
	{"tgei"},
	{"tgeiu"},
	{"tlti"},
	{"tltiu"},
	{"teqi"},
	{"resvd_13"},
	{"tnei"},
	{"resvd_15"},
	{"bltzal"},
	{"bgezal"},
	{"bltzall"},
	{"bgezall"},
	{"resvd_20"},
	{"resvd_21"},
	{"resvd_22"},
	{"resvd_23"},
	{"mtsab"},
	{"mtsah"},
	{"resvd_26"},
	{"resvd_27"},
	{"resvd_28"},
	{"resvd_29"},
	{"resvd_30"},
	{"resvd_31"}
};

extern const InsnInfo MMI_TABLE[MAX_MMI] = {
	{"madd"},
	{"maddu"},
	{"resvd_2"},
	{"resvd_3"},
	{"plzcw"},
	{"resvd_5"},
	{"resvd_6"},
	{"resvd_7"},
	{"mmi0"},
	{"mmi2"},
	{"resvd_10"},
	{"resvd_11"},
	{"resvd_12"},
	{"resvd_13"},
	{"resvd_14"},
	{"resvd_15"},
	{"mfhi1"},
	{"mthi1"},
	{"mflo1"},
	{"mtlo1"},
	{"resvd_20"},
	{"resvd_21"},
	{"resvd_22"},
	{"resvd_23"},
	{"mult1"},
	{"multu1"},
	{"div1"},
	{"divu1"},
	{"resvd_28"},
	{"resvd_29"},
	{"resvd_30"},
	{"resvd_31"},
	{"madd1"},
	{"maddu1"},
	{"resvd_34"},
	{"resvd_35"},
	{"resvd_36"},
	{"resvd_37"},
	{"resvd_38"},
	{"resvd_39"},
	{"mmi1"},
	{"mmi3"},
	{"resvd_42"},
	{"resvd_43"},
	{"resvd_44"},
	{"resvd_45"},
	{"resvd_46"},
	{"resvd_47"},
	{"pmfhl"},
	{"pmthl"},
	{"resvd_50"},
	{"resvd_51"},
	{"psllh"},
	{"resvd_53"},
	{"psrlh"},
	{"psrah"},
	{"resvd_56"},
	{"resvd_57"},
	{"resvd_58"},
	{"resvd_59"},
	{"psllw"},
	{"resvd_61"},
	{"psrlw"},
	{"psraw"}
};

extern const InsnInfo MMI0_TABLE[MAX_MMI0] = {
	{"paddw"},
	{"psubw"},
	{"pcgtw"},
	{"pmaxw"},
	{"paddh"},
	{"psubh"},
	{"pcgth"},
	{"pmaxh"},
	{"paddb"},
	{"psubb"},
	{"pcgtb"},
	{"resvd_11"},
	{"resvd_12"},
	{"resvd_13"},
	{"resvd_14"},
	{"resvd_15"},
	{"paddsw"},
	{"psubsw"},
	{"pextlw"},
	{"ppacw"},
	{"paddsh"},
	{"psubsh"},
	{"pextlh"},
	{"ppach"},
	{"paddsb"},
	{"psubsb"},
	{"pextlb"},
	{"ppacb"},
	{"resvd_28"},
	{"resvd_29"},
	{"pext5"},
	{"ppac5"}
};

extern const InsnInfo MMI1_TABLE[MAX_MMI1] = {
	{"resvd_0"},
	{"pabsw"},
	{"pceqw"},
	{"pminw"},
	{"padsbh"},
	{"pabsh"},
	{"pceqh"},
	{"pminh"},
	{"resvd_8"},
	{"resvd_9"},
	{"pceqb"},
	{"resvd_11"},
	{"resvd_12"},
	{"resvd_13"},
	{"resvd_14"},
	{"resvd_15"},
	{"padduw"},
	{"psubuw"},
	{"pextuw"},
	{"resvd_19"},
	{"padduh"},
	{"psubuh"},
	{"pextuh"},
	{"resvd_23"},
	{"paddub"},
	{"psubub"},
	{"pextub"},
	{"qfsrv"},
	{"resvd_28"},
	{"resvd_29"},
	{"resvd_30"},
	{"resvd_31"}
};

extern const InsnInfo MMI2_TABLE[MAX_MMI2] = {
	{"pmaddw"},
	{"resvd_1"},
	{"psllvw"},
	{"psrlvw"},
	{"pmsubw"},
	{"resvd_5"},
	{"resvd_6"},
	{"resvd_7"},
	{"pmfhi"},
	{"pmflo"},
	{"pinth"},
	{"resvd_11"},
	{"pmultw"},
	{"pdivw"},
	{"pcpyld"},
	{"resvd_15"},
	{"pmaddh"},
	{"phmadh"},
	{"pand"},
	{"pxor"},
	{"pmsubh"},
	{"phmsbh"},
	{"resvd_22"},
	{"resvd_23"},
	{"resvd_24"},
	{"resvd_25"},
	{"pexeh"},
	{"prevh"},
	{"pmulth"},
	{"pdivbw"},
	{"pexew"},
	{"prot3w"}
};

extern const InsnInfo MMI3_TABLE[MAX_MMI3] = {
	{"pmadduw"},
	{"resvd_1"},
	{"resvd_2"},
	{"psravw"},
	{"resvd_4"},
	{"resvd_5"},
	{"resvd_6"},
	{"resvd_7"},
	{"pmthi"},
	{"pmtlo"},
	{"pinteh"},
	{"resvd_11"},
	{"pmultuw"},
	{"pdivuw"},
	{"pcpyud"},
	{"resvd_15"},
	{"resvd_16"},
	{"resvd_17"},
	{"por"},
	{"pnor"},
	{"resvd_20"},
	{"resvd_21"},
	{"resvd_22"},
	{"resvd_23"},
	{"resvd_24"},
	{"resvd_25"},
	{"pexch"},
	{"pcpyh"},
	{"resvd_28"},
	{"resvd_29"},
	{"pexcw"},
	{"resvd_31"}
};

extern const InsnInfo COP0_TABLE[MAX_COP0] = {
	{"mf0"},
	{"resvd_1"},
	{"resvd_2"},
	{"resvd_3"},
	{"mt0"},
	{"resvd_5"},
	{"resvd_6"},
	{"resvd_7"},
	{"bc0"},
	{"resvd_9"},
	{"resvd_10"},
	{"resvd_11"},
	{"resvd_12"},
	{"resvd_13"},
	{"resvd_14"},
	{"resvd_15"},
	{"c0"},
	{"resvd_17"},
	{"resvd_18"},
	{"resvd_19"},
	{"resvd_20"},
	{"resvd_21"},
	{"resvd_22"},
	{"resvd_23"},
	{"resvd_24"},
	{"resvd_25"},
	{"resvd_26"},
	{"resvd_27"},
	{"resvd_28"},
	{"resvd_29"},
	{"resvd_30"},
	{"resvd_31"}
};

extern const InsnInfo COP0_BC0_TABLE[MAX_BC0] = {
	{"bc0f"},
	{"bc0t"},
	{"bc0fl"},
	{"bc0tl"},
	{"resvd_4"},
	{"resvd_5"},
	{"resvd_6"},
	{"resvd_7"},
	{"resvd_8"},
	{"resvd_9"},
	{"resvd_10"},
	{"resvd_11"},
	{"resvd_12"},
	{"resvd_13"},
	{"resvd_14"},
	{"resvd_15"},
	{"resvd_16"},
	{"resvd_17"},
	{"resvd_18"},
	{"resvd_19"},
	{"resvd_20"},
	{"resvd_21"},
	{"resvd_22"},
	{"resvd_23"},
	{"resvd_24"},
	{"resvd_25"},
	{"resvd_26"},
	{"resvd_27"},
	{"resvd_28"},
	{"resvd_29"},
	{"resvd_30"},
	{"resvd_31"}
};

extern const InsnInfo COP0_C0_TABLE[MAX_C0] = {
	{"undef_0"},
	{"tlbr"},
	{"tlbwi"},
	{"undef_3"},
	{"undef_4"},
	{"undef_5"},
	{"tlbwr"},
	{"undef_7"},
	{"tlbp"},
	{"undef_9"},
	{"undef_10"},
	{"undef_11"},
	{"undef_12"},
	{"undef_13"},
	{"undef_14"},
	{"undef_15"},
	{"undef_16"},
	{"undef_17"},
	{"undef_18"},
	{"undef_19"},
	{"undef_20"},
	{"undef_21"},
	{"undef_22"},
	{"undef_23"},
	{"eret"},
	{"undef_25"},
	{"undef_26"},
	{"undef_27"},
	{"undef_28"},
	{"undef_29"},
	{"undef_30"},
	{"undef_31"},
	{"undef_32"},
	{"undef_33"},
	{"undef_34"},
	{"undef_35"},
	{"undef_36"},
	{"undef_37"},
	{"undef_38"},
	{"undef_39"},
	{"undef_40"},
	{"undef_41"},
	{"undef_42"},
	{"undef_43"},
	{"undef_44"},
	{"undef_45"},
	{"undef_46"},
	{"undef_47"},
	{"undef_48"},
	{"undef_49"},
	{"undef_50"},
	{"undef_51"},
	{"undef_52"},
	{"undef_53"},
	{"undef_54"},
	{"undef_55"},
	{"ei"},
	{"di"},
	{"undef_58"},
	{"undef_59"},
	{"undef_60"},
	{"undef_61"},
	{"undef_62"},
	{"undef_63"}
};

extern const InsnInfo COP1_TABLE[MAX_COP1] = {
	{"mfc1"},
	{"resvd_1"},
	{"cfc1"},
	{"resvd_3"},
	{"mtc1"},
	{"resvd_5"},
	{"ctc1"},
	{"resvd_7"},
	{"bc1"},
	{"resvd_9"},
	{"resvd_10"},
	{"resvd_11"},
	{"resvd_12"},
	{"resvd_13"},
	{"resvd_14"},
	{"resvd_15"},
	{"s"},
	{"resvd_17"},
	{"resvd_18"},
	{"resvd_19"},
	{"w"},
	{"resvd_21"},
	{"resvd_22"},
	{"resvd_23"},
	{"resvd_24"},
	{"resvd_25"},
	{"resvd_26"},
	{"resvd_27"},
	{"resvd_28"},
	{"resvd_29"},
	{"resvd_30"},
	{"resvd_31"}
};

extern const InsnInfo COP1_BC1_TABLE[MAX_BC1] = {
	{"bc1f"},
	{"bc1t"},
	{"bc1fl"},
	{"bc1tl"},
	{"resvd_4"},
	{"resvd_5"},
	{"resvd_6"},
	{"resvd_7"},
	{"resvd_8"},
	{"resvd_9"},
	{"resvd_10"},
	{"resvd_11"},
	{"resvd_12"},
	{"resvd_13"},
	{"resvd_14"},
	{"resvd_15"},
	{"resvd_16"},
	{"resvd_17"},
	{"resvd_18"},
	{"resvd_19"},
	{"resvd_20"},
	{"resvd_21"},
	{"resvd_22"},
	{"resvd_23"},
	{"resvd_24"},
	{"resvd_25"},
	{"resvd_26"},
	{"resvd_27"},
	{"resvd_28"},
	{"resvd_29"},
	{"resvd_30"},
	{"resvd_31"}
};

extern const InsnInfo COP1_S_TABLE[MAX_S] = {
	{"ADD"},
	{"SUB"},
	{"MUL"},
	{"DIV"},
	{"SQRT"},
	{"ABS"},
	{"MOV"},
	{"NEG"},
	{"UNDEF_8"},
	{"UNDEF_9"},
	{"UNDEF_10"},
	{"UNDEF_11"},
	{"UNDEF_12"},
	{"UNDEF_13"},
	{"UNDEF_14"},
	{"UNDEF_15"},
	{"UNDEF_16"},
	{"UNDEF_17"},
	{"UNDEF_18"},
	{"UNDEF_19"},
	{"UNDEF_20"},
	{"UNDEF_21"},
	{"RSQRT"},
	{"UNDEF_23"},
	{"ADDA"},
	{"SUBA"},
	{"MULA"},
	{"UNDEF_27"},
	{"MADD"},
	{"MSUB"},
	{"MADDA"},
	{"MSUBA"},
	{"UNDEF_32"},
	{"UNDEF_33"},
	{"UNDEF_34"},
	{"UNDEF_35"},
	{"CVTW"},
	{"UNDEF_37"},
	{"UNDEF_38"},
	{"UNDEF_39"},
	{"MAX"},
	{"MIN"},
	{"UNDEF_42"},
	{"UNDEF_43"},
	{"UNDEF_44"},
	{"UNDEF_45"},
	{"UNDEF_46"},
	{"UNDEF_47"},
	{"C_F"},
	{"UNDEF_49"},
	{"C_EQ"},
	{"UNDEF_51"},
	{"C_LT"},
	{"UNDEF_53"},
	{"C_LE"},
	{"UNDEF_55"},
	{"UNDEF_56"},
	{"UNDEF_57"},
	{"UNDEF_58"},
	{"UNDEF_59"},
	{"UNDEF_60"},
	{"UNDEF_61"},
	{"UNDEF_62"},
	{"UNDEF_63"}
};

extern const InsnInfo COP1_W_TABLE[MAX_W] = {
	{"undef_0"},
	{"undef_1"},
	{"undef_2"},
	{"undef_3"},
	{"undef_4"},
	{"undef_5"},
	{"undef_6"},
	{"undef_7"},
	{"undef_8"},
	{"undef_9"},
	{"undef_10"},
	{"undef_11"},
	{"undef_12"},
	{"undef_13"},
	{"undef_14"},
	{"undef_15"},
	{"undef_16"},
	{"undef_17"},
	{"undef_18"},
	{"undef_19"},
	{"undef_20"},
	{"undef_21"},
	{"undef_22"},
	{"undef_23"},
	{"undef_24"},
	{"undef_25"},
	{"undef_26"},
	{"undef_27"},
	{"undef_28"},
	{"undef_29"},
	{"undef_30"},
	{"undef_31"},
	{"cvts"},
	{"undef_33"},
	{"undef_34"},
	{"undef_35"},
	{"undef_36"},
	{"undef_37"},
	{"undef_38"},
	{"undef_39"},
	{"undef_40"},
	{"undef_41"},
	{"undef_42"},
	{"undef_43"},
	{"undef_44"},
	{"undef_45"},
	{"undef_46"},
	{"undef_47"},
	{"undef_48"},
	{"undef_49"},
	{"undef_50"},
	{"undef_51"},
	{"undef_52"},
	{"undef_53"},
	{"undef_54"},
	{"undef_55"},
	{"undef_56"},
	{"undef_57"},
	{"undef_58"},
	{"undef_59"},
	{"undef_60"},
	{"undef_61"},
	{"undef_62"},
	{"undef_63"}
};

}
